### ISSUE TITLE
Andriod demo keeps running a circle

### ISSUE THREAD

**Issue by StevenJokes** [aws-samples/djl-demo#86]
19:05	Executing tasks: [:quickdraw_recognition:assembleDebug] in project D:\onedrive\Documents\code\AndroidStudioProjects\djl-demo-android

19:05	Gradle build finished in 1 s 252 ms

19:05	Emulator: VK_VERSION_1_1 check failed: vkBindBufferMemory2 not found

19:05	Emulator: VK_VERSION_1_1 check failed: vkBindImageMemory2 not found

19:05	Emulator: VK_VERSION_1_1 check failed: vkGetDeviceGroupPeerMemoryFeatures not found

19:05	Emulator: VK_VERSION_1_1 check failed: vkCmdSetDeviceMask not found

19:05	Emulator: VK_VERSION_1_1 check failed: vkCmdDispatchBase not found

19:05	Emulator: VK_VERSION_1_1 check failed: vkGetImageMemoryRequirements2 not found

19:05	Emulator: VK_VERSION_1_1 check failed: vkGetBufferMemoryRequirements2 not found

19:05	Emulator: VK_VERSION_1_1 check failed: vkGetImageSparseMemoryRequirements2 not found

19:05	Emulator: VK_VERSION_1_1 check failed: vkTrimCommandPool not found

19:05	Emulator: VK_VERSION_1_1 check failed: vkCreateSamplerYcbcrConversion not found

19:05	Emulator: VK_VERSION_1_1 check failed: vkDestroySamplerYcbcrConversion not found

19:05	Emulator: VK_VERSION_1_1 check failed: vkCreateDescriptorUpdateTemplate not found

19:05	Emulator: VK_VERSION_1_1 check failed: vkDestroyDescriptorUpdateTemplate not found

19:05	Emulator: VK_VERSION_1_1 check failed: vkUpdateDescriptorSetWithTemplate not found

19:05	Emulator: VK_VERSION_1_1 check failed: vkGetDescriptorSetLayoutSupport not found

19:05	Emulator: createOrGetGlobalVkEmulation: Warning: Vulkan 1.1 APIs missing from device

19:05	Emulator: socketTcpLoopbackClientFor: error: fd 89476 above FD_SETSIZE (32768)

19:05	Emulator: socketTcpLoopbackClientFor: error: fd 89476 above FD_SETSIZE (32768)

19:05	Emulator: emulator: ERROR: AdbHostServer.cpp:102: Unable to connect to adb daemon on port: 5037

19:05	Emulator: socketTcpLoopbackClientFor: error: fd 106312 above FD_SETSIZE (32768)

19:05	Emulator: socketTcpLoopbackClientFor: error: fd 106312 above FD_SETSIZE (32768)

19:05	Emulator: socketTcpLoopbackClientFor: error: fd 108400 above FD_SETSIZE (32768)

19:05	Emulator: socketTcpLoopbackClientFor: error: fd 108400 above FD_SETSIZE (32768)

19:05	Install successfully finished in 2 s 221 ms.: App restart successful without requiring a re-install.

---

![image](https://user-images.githubusercontent.com/25657787/88477555-a256af00-cf73-11ea-9476-22ac2cf77002.png)

---
Executing tasks: [:quickdraw_recognition:assembleDebug] in project D:\onedrive\Documents\code\AndroidStudioProjects\djl-demo-android

> Task :quickdraw_recognition:preBuild UP-TO-DATE
> Task :quickdraw_recognition:preDebugBuild UP-TO-DATE
> Task :quickdraw_recognition:compileDebugAidl NO-SOURCE
> Task :quickdraw_recognition:generateDebugBuildConfig UP-TO-DATE
> Task :quickdraw_recognition:javaPreCompileDebug UP-TO-DATE
> Task :quickdraw_recognition:compileDebugRenderscript NO-SOURCE
> Task :quickdraw_recognition:generateDebugResValues UP-TO-DATE
> Task :quickdraw_recognition:generateDebugResources UP-TO-DATE
> Task :quickdraw_recognition:mergeDebugResources UP-TO-DATE
> Task :quickdraw_recognition:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :quickdraw_recognition:extractDeepLinksDebug UP-TO-DATE
> Task :quickdraw_recognition:processDebugManifest UP-TO-DATE
> Task :quickdraw_recognition:processDebugResources UP-TO-DATE
> Task :quickdraw_recognition:compileDebugJavaWithJavac UP-TO-DATE
> Task :quickdraw_recognition:compileDebugSources UP-TO-DATE
> Task :quickdraw_recognition:mergeDebugShaders UP-TO-DATE
> Task :quickdraw_recognition:compileDebugShaders NO-SOURCE
> Task :quickdraw_recognition:generateDebugAssets UP-TO-DATE
> Task :quickdraw_recognition:mergeDebugAssets UP-TO-DATE
> Task :quickdraw_recognition:processDebugJavaRes NO-SOURCE
> Task :quickdraw_recognition:mergeDebugJavaResource UP-TO-DATE
> Task :quickdraw_recognition:desugarDebugFileDependencies UP-TO-DATE
> Task :quickdraw_recognition:checkDebugDuplicateClasses UP-TO-DATE
> Task :quickdraw_recognition:mergeExtDexDebug UP-TO-DATE
> Task :quickdraw_recognition:mergeLibDexDebug UP-TO-DATE
> Task :quickdraw_recognition:dexBuilderDebug UP-TO-DATE
> Task :quickdraw_recognition:mergeProjectDexDebug UP-TO-DATE
> Task :quickdraw_recognition:mergeDebugJniLibFolders UP-TO-DATE
> Task :quickdraw_recognition:validateSigningDebug UP-TO-DATE
> Task :quickdraw_recognition:mergeDebugNativeLibs UP-TO-DATE
> Task :quickdraw_recognition:stripDebugDebugSymbols UP-TO-DATE
> Task :quickdraw_recognition:packageDebug UP-TO-DATE
> Task :quickdraw_recognition:assembleDebug UP-TO-DATE

BUILD SUCCESSFUL in 957ms
23 actionable tasks: 23 up-to-date

Build Analyzer results available

---

gradle dependency all have installed.

Runing on the simulator :Pixel XL API 30

---

07/26 19:35:13: Launching 'quickdraw_recognition' on Pixel XL API 30.
$ adb shell am start -n "ai.djl.examples.quickdraw/ai.djl.examples.quickdraw.DoodleDrawActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: ai.djl.examples.quickdraw.test | ai.djl.examples.quickdraw
Waiting for application to come online: ai.djl.examples.quickdraw.test | ai.djl.examples.quickdraw
Connected to process 7035 on device 'emulator-5554'.
Waiting for application to come online: ai.djl.examples.quickdraw.test | ai.djl.examples.quickdraw
Connecting to ai.djl.examples.quickdraw
Connected to the target VM, address: 'localhost:8630', transport: 'socket'
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/mples.quickdra: Not late-enabling -Xcheck:jni (already on)
I/mples.quickdra: Unquickening 12 vdex files!
W/mples.quickdra: Unexpected CPU variant for X86 using defaults: x86
W/ActivityThread: Application ai.djl.examples.quickdraw is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/chatty: uid=10155(ai.djl.examples.quickdraw) identical 3 lines
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/chatty: uid=10155(ai.djl.examples.quickdraw) identical 1 line
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1494)
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
W/mples.quickdra: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/mples.quickdra: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
D/HostConnection: HostConnection::get() New Host Connection established 0xf22797f0, tid 7160
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/EGL_emulation: eglCreateContext: 0xf2062c90: maj 2 min 0 rcv 2
D/EGL_emulation: eglMakeCurrent: 0xf2062c90: ver 2 0 (tinfo 0xc39b3c50) (first time)
I/Gralloc4: mapper 4.x is not supported
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0xf2278290, tid 7160
D/goldfish-address-space: allocate: Ask for block of size 0x100
    allocate: ioctl allocate returned offset 0x3f700f000 size 0x2000
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
I/Choreographer: Skipped 48 frames!  The application may be doing too much work on its main thread.
Disconnected from the target VM, address: 'localhost:8630', transport: 'socket'

---

Maybe it is caused by
**I/Gralloc4: mapper 4.x is not supported**

**Comment by StevenJokes** [comment]
Then I tried to install on my HUAWEI JSN-AL00a. It works after loading 2 min.
Why?

**Comment by StevenJokes** [comment]
I guess it is caused by simulator 's not having network.
![image](https://user-images.githubusercontent.com/25657787/88479135-97098080-cf7f-11ea-8ae8-92b32078aa29.png)
Maybe we can download the model first in demo repo to avoid requiring the network.

**Comment by lanking520** [comment]
Historically we used to download the model to  the asset folder and load it to the machine. For simplicity, we are using the URL option to load the model. DJL can load the model directly from file by specify the url to a file path. @frankfliu

**Comment by frankfliu** [comment]
@StevenJokes you are right, DJL trying to download the model from specified URL on the first time app is started. You can go back to older version: https://github.com/aws-samples/djl-demo/blob/6001e3748f85429d8ef10d11ad52dc38e4f451fc/android/quickdraw_recognition/src/main/java/ai/djl/examples/quickdraw/DoodleRecognitionActivity.java#L43

to avoid download the model at runtime, but the package will be increased.

**Comment by StevenJokes** [comment]
We should put what we downloaded from URL to models/doodle_mobilenet.pt?  just to confirm it.

**Comment by lanking520** [comment]
You can use the complete project to build and test:

https://github.com/aws-samples/djl-demo/tree/9ef6ac75f6d644ecefe809019969b8d2697a3b68/android . 

You can call a command in [here](https://github.com/aws-samples/djl-demo/tree/9ef6ac75f6d644ecefe809019969b8d2697a3b68/android#setup) to download the model and then just simply build the project

**Comment by StevenJokes** [comment]
Thanks.
